### PR TITLE
#166816054 setup testing frameworks 

### PR DESCRIPTION
**Pull request by devPinheiro**
#### What does this PR do?
- It contains setup of unit, integration and end-to-end test suites

#### Description of Task to be completed?
- install jest and enzyme
- configure jest and enzyme
- install cypress for end-to-end tests
- add test scripts to package.json
- write unit tests
- write end-to-end test

#### Any background context you want to provide?
none

#### What are the relevant pivotal tracker stories?
- PT Story link - `[#166816054] (https://www.pivotaltracker.com/story/show/166816054)`

### CODE REVIEW

**Comment by dharmykoya** [comment]
Looks good to me

**Comment by dharmykoya** [comment]
Samuel well done but please would you squash your commit into one to make rebasing easier.
thank you

**Comment by devPinheiro** [comment]
> Samuel well done but please would you squash your commit into one to make rebasing easier.
> thank you

**Review by tunedev — APPROVED** [review]
LGTM

**Comment by fxola** [comment]
Great work Sam LGTM

**Review by fxola — APPROVED** [review]

**Pull request merged**
