### PR TITLE
#166816070 article likes and dislikes feature

### PR DESCRIPTION
**Pull request by devPinheiro**
#### What does this PR do?
- It contains  a feature for the article like/dislike feature

#### Description of Task to be completed?
- add article like action
- write tests

#### How should this be manually tested?
- After cloning the repo, cd into the root folder

- Install all necessary dependencies by running 

  ``npm install``

- Launch the node server with

  ``npm run dev``

- Using a web browser visit the link below:

  ``localhost:8080/``

- To run local tests using Jest
  
  ``npm test``

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- PT Story link - `[ #166816070

] (https://www.pivotaltracker.com/story/show/166816070)`

Screenshot 2019-08-27 at 10 23 08 AM

### CODE REVIEW

**Comment by dharmykoya** [comment]
Looks good to me

**Comment by halimahO** [comment]
LGTM

**Review by fxola — APPROVED** [review]
LGTM

**Review by tunedev — APPROVED** [review]
Good job. LGTM

**Pull request merged**
