### PR TITLE
#167620776 Create reusable Author Card Component

### PR DESCRIPTION
**Pull request by fxola**
#### What does this PR do?
- Create reusable Author Card Component

#### Description of Task to be completed?
- write author card component
- write styling for author card component
- create demo article template and link to app
- add sample image
- write author card component test
- delivers [#167620776]

#### How should this be manually tested?
- Clone the repository using ```git clone https://github.com/andela/persephone-ah-frontend.git .``` in your terminal
- run ```npm install``` on your terminal
- run ```npm run start``` to start up the server
- run ```npm test``` to see test results
#### Any background context you want to provide?
-N/A
#### What are the relevant pivotal tracker stories?
- PT Story link - [#167620776](https://www.pivotaltracker.com/n/projects/2353116/stories/167620776)

#### Screenshots (if appropriate)
Screenshot 2019-08-01 at 7 32 25 PM

#### Questions:
- N/A

### CODE REVIEW

**Comment by halimahO** [comment]
LGTM

**Comment by dharmykoya** [comment]
Looks good to me... but we need the light mode of it

**Review by tunedev — APPROVED** [review]
LGTM

**Comment by fxola** [comment]
> Looks good to me... but we need the light mode of it

Yea thanks for pointing that out. done already

**Pull request merged**
